--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xila-pm-pl/XilaShopGUI
build-by-default: true
branches:
- master
projects:
  XilaShopGUI:
    path: ""
    libs:
      - src: muqsit/invmenu/InvMenu
        version: ^4.5.1
        branch: "4.0"
      
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.2
        branch: "master"

    lint: 
     phpstan: false 
...
