
---

name: ShopGUI

version: 1.0.0

main: shopgui\plugins\Loader

api: 4.0.0

# idk why i left space good looking code na ???

author: XilaPMPL

description: This is plugin Economy Shop with GUI, the plugin in Server Minecraft Pocket Edition -=Poketimine-MP=-

...
